version: '3.8'

services:

  mailSender:
    image: 'docker-spring-boot:latest'
    ports:
      - "8081:8081"
    build:
      context: .
    container_name: mailSender
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - mailSender
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
