version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: danekerscode-social-media-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/social_media_api
      db-username: postgres
      db-password: qwerty
    restart: always

  db:
    image: 'postgres:15.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=social_media_api
    ports:
      - "5432:5432"

