spring:
  application:
    name: mail-sender
  mail:
    from: socialmedia@gmail.com
    host: smtp.gmail.com
    port: 587
    password: /
    protocol: mail.transport.protocol
    protocolType: smtp
    mailDebug: mail.debug
    danekerscode: true
    enable: mail.smtp.starttls.enable
    username: kkraken2005@gmail.com
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    topics:
      mail: mail_topic

server:
  port: 8181
